### ISSUE TITLE
bert 无法跑通

### ISSUE THREAD

**Issue by BBuf** [thu-pacman/PET#5]
在 NVIDIA GPU 环境下克隆此工程并编译运行。

首先使用 `PET_DCU/benchmark/models/scripts/bert_onnx.py` 导出了bert的onnx文件，然后编译了DCU之后在build下执行：

`./onnx_origin ../benchmark/models/scripts/mybert-new.onnx`

此时会尝试导入ONNX到PET的Graph中，这个时候发生了报错：

```bash
onnx_origin: /home/PET_DCU/include/operator.h:1795: tpm::ReshapeOp::ReshapeOp(tpm::Tensor *, tpm::Tensor *): Assertion `input->size() == output->size()' failed.
Aborted (core dumped)
```

可以看到挂在Reshape Op的形状检查，我打印了一下`input->size()` 和 `output->size()` ，分别为：

```
589824 37748736
```

所以输出Tensor的size是输入的64倍，这个64是导出ONNX时的batch_size，希望可以解答这个错误的原因是什么

**Comment by whjthu** [comment]
你好，问题的原因是我们之前的一次修改中把 $[b, m, n], [n, k]$ 形状的矩阵乘及其相关算子进行了一些调整，导致出现该 bug。我们目前正在修复。这个问题的本质是 Reshape 接口是否要拥有 copy 语义，你们那边的调试过程中可以先把这行 assert 去掉，不影响图优化部分的功能和正确性，我们也会尽快修复该问题。
另外建议使用 models-ae 里面的模型生成，benchmark/models/scripts 下的脚本有些是 out of date 的

**Comment by BBuf** [comment]
> 你好，问题的原因是我们之前的一次修改中把 [b,m,n],[n,k] 形状的矩阵乘及其相关算子进行了一些调整，导致出现该 bug。我们目前正在修复。这个问题的本质是 Reshape 接口是否要拥有 copy 语义，你们那边的调试过程中可以先把这行 assert 去掉，不影响图优化部分的功能和正确性，我们也会尽快修复该问题。 另外建议使用 models-ae 里面的模型生成，benchmark/models/scripts 下的脚本有些是 out of date 的

好的。注释掉assert之后又出现了新的错误：

```bash
terminate called after throwing an instance of 'pybind11::error_already_set'
  what():  TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. cpp_module.PermItem()
    2. cpp_module.PermItem(arg0: List[int])
    3. cpp_module.PermItem(arg0: std::initializer_list<int>)

Invoked with: 0

Did you forget to `#include <pybind11/stl.h>`? Or <pybind11/complex.h>,
<pybind11/functional.h>, <pybind11/chrono.h>, etc. Some automatic
conversions are optional and require extra headers to be included
when compiling your pybind11 module.

At:
  /home/zhangxiaoyu/anaconda3/lib/python3.8/site-packages/tpm-0.1-py3.8-linux-x86_64.egg/cpp_plugin/import_onnx.py(417): <listcomp>
  /home/zhangxiaoyu/anaconda3/lib/python3.8/site-packages/tpm-0.1-py3.8-linux-x86_64.egg/cpp_plugin/import_onnx.py(417): import_onnx

Aborted (core dumped)
```

烦请再帮忙看一下
